# Generated by Django 5.2 on 2025-05-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0004_category_main_category_transaction_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.user')),
            ],
        ),
    ]
