# Generated by Django 5.2 on 2025-05-26 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('financeiro', '0004_category_main_category_transaction_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarylink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_links', to='financeiro.user'),
        ),
    ]
