# Generated by Django 5.2 on 2025-04-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], default='receita', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
